version: "3.6"

services:
  db:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
  web:
    build: ./web
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/src/app
    command: bin/rails s -p 3000 -b '0.0.0.0'
